#! /usr/bin/env python3

################################################################################################################################################################
# Program combines raw reads from two lanes and renames the files. It assumes that the files in both lanes have the same name. Also it assumes that the
# samples are paired ended
################################################################################################################################################################

lane1_directory = "/90daydata/maizegdb/sagnik/Corn_vs_PS/data/lane1"
lane2_directory = "/90daydata/maizegdb/sagnik/Corn_vs_PS/data/lane2"
output_directory = "/90daydata/maizegdb/sagnik/Corn_vs_PS/data/merged"

import glob
import sys
import os

os.system(f"mkdir -p {output_directory}")

lane1_files = glob.glob(f"{lane1_directory}/*gz")
lane2_files = glob.glob(f"{lane2_directory}/*gz")

if len(lane1_files)!=len(lane2_files):
    print("There must be same number of files in each directory")
    sys.exit()
    
for filepath in lane1_files:
    filename = filepath.split("/")[-1]
    filepath_lane1 = filepath
    filepath_lane2 = f"{lane2_directory}/{filename.replace('_L001_','_L002_')}"
    if "_R1_" in filename:
        output_filename = f"{output_directory}/{filename.split('_')[0]}_1.fastq.gz"
    else:
        output_filename = f"{output_directory}/{filename.split('_')[0]}_2.fastq.gz"
    
    cmd = f"cat {filepath_lane1} {filepath_lane2} > {output_filename}"
    print(f"Executing {cmd}")
    os.system(cmd)