#!/bin/bash

#SBATCH -n 72
#SBATCH -N 1
#SBATCH --partition=long
##SBATCH --partition=priority-mem768
#SBATCH --qos=maizegdb
#SBATCH --mem=200G
#SBATCH --time=14-00:00:00
#SBATCH --job-name="IA16"
#SBATCH --mail-user=sagnikbanerjee@gmail.com
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/project/maizegdb/sagnik/CORN_VS_PS/data/analysis_with_IA16_isolate.output
#SBATCH --error=/project/maizegdb/sagnik/CORN_VS_PS/data/analysis_with_IA16_isolate.error

module load singularity

ROOT_DIR="/project/maizegdb/sagnik/CORN_VS_PS/"
TEMP_DIR="/90daydata/maizegdb/sagnik/CORN_VS_PS/analysis_with_IA16_isolate"
REF_DIR="/project/maizegdb/sagnik/CORN_VS_PS/data/PS_SALSA_annotation/final_annotation/"

${ROOT_DIR}/Corn_vs_PS/find_differentially_expressed_genes \
--transfer \
--metadatafilename ${ROOT_DIR}/Corn_vs_PS/metadata.csv \
--output_directory ${ROOT_DIR}/data/analysis_with_IA16_isolate \
--temp_directory ${TEMP_DIR} \
--framework singularity \
--cpu 72 \
--reference ${REF_DIR}/B73_IA16_gg_nd_merged.fasta \
--gene_to_transcript_map ${REF_DIR}/transcript_to_gene_map \
1> ${ROOT_DIR}/data/analysis_with_IA16_isolate.output \
2> ${ROOT_DIR}/data/analysis_with_IA16_isolate.error