#!/bin/bash

#SBATCH -n 40
#SBATCH -N 1
#SBATCH --partition=long
##SBATCH --partition=priority-mem768
#SBATCH --qos=maizegdb
#SBATCH --mem=100G
#SBATCH --time=14-00:00:00
#SBATCH --job-name="Annotate_Fungal_Genome"
#SBATCH --mail-user=sagnik@iastate.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/project/maizegdb/sagnik/CORN_VS_PS/data/PS_SALSA_annotation.output
#SBATCH --error=/project/maizegdb/sagnik/CORN_VS_PS/data/PS_SALSA_annotation.error

module load singularity

ROOT_DIR="/project/maizegdb/sagnik/CORN_VS_PS"
TEMP_DIR="/90daydata/maizegdb/sagnik/CORN_VS_PS"
REF_DIR="/90daydata/maizegdb/sagnik/CORN_VS_PS/data/reference"

{ROOT_DIR}/annotate_fungal_genome \
--metadatafilename ${ROOT_DIR}/Corn_vs_PS/metadata.csv \
--output_directory ${ROOT_DIR}/data/PS_SALSA_annotation \
--genome_references ${REF_DIR}/combined_B73_PS_SALSA/genome.fasta \
--cpu 40 \
--temp_directory ${TEMP_DIR}/PS_SALSA_annotation \
--transfer \
--framework singularity \
1> ${ROOT_DIR}/data/PS_SALSA_annotation.output \
2> ${ROOT_DIR}/data/PS_SALSA_annotation.error