#!/bin/bash

#SBATCH -n 72
#SBATCH -N 1
#SBATCH --partition=long
##SBATCH --partition=priority-mem768
#SBATCH --qos=maizegdb
#SBATCH --mem=300G
#SBATCH --time=14-00:00:00
#SBATCH --job-name="Transmeta"
#SBATCH --mail-user=sagnikbanerjee15@gmail.com
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/project/maizegdb/sagnik/CORN_VS_PS/data/PS_SALSA_annotation.output
#SBATCH --error=/project/maizegdb/sagnik/CORN_VS_PS/data/PS_SALSA_annotation.error

module load singularity

ROOT_DIR="/project/maizegdb/sagnik/CORN_VS_PS"
TEMP_DIR="/90daydata/maizegdb/sagnik/CORN_VS_PS"
REF_DIR="/90daydata/maizegdb/sagnik/CORN_VS_PS/data/reference"

singularity exec \
-B ${ROOT_DIR}/data/PS_SALSA_annotation/alignments:${ROOT_DIR}/data/PS_SALSA_annotation/alignments \
${ROOT_DIR}/data/PS_SALSA_annotation/singularity_images/transmeta_0.0.1.sif \
bash -c "TransMeta \
--bam ${ROOT_DIR}/data/PS_SALSA_annotation/alignments/list_of_bam_files \
--strand unstranded \
--output_dir ${ROOT_DIR}/data/PS_SALSA_annotation/alignments/transmeta_assembly_output \
--min_trans_length 100 \
-p 72 \
1> ${ROOT_DIR}/data/PS_SALSA_annotation/alignments/transmeta_assembly_output.output \ 
2> ${ROOT_DIR}/data/PS_SALSA_annotation/alignments/transmeta_assembly_output.error "

