#!/bin/bash

#SBATCH -n 72
#SBATCH -N 1
#SBATCH --partition=long
##SBATCH --partition=priority-mem768
#SBATCH --qos=maizegdb
#SBATCH --mem=500G
#SBATCH --time=14-00:00:00
#SBATCH --job-name="Stringtie"
#SBATCH --mail-user=sagnikbanerjee15@gmail.com
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/project/maizegdb/sagnik/CORN_VS_PS/data/PS_SALSA_annotation/alignments/stringtie_all_merged.output
#SBATCH --error=/project/maizegdb/sagnik/CORN_VS_PS/data/PS_SALSA_annotation/alignments/stringtie_all_merged.error

module load singularity

ROOT_DIR="/project/maizegdb/sagnik/CORN_VS_PS"
TEMP_DIR="/90daydata/maizegdb/sagnik/CORN_VS_PS"
REF_DIR="/90daydata/maizegdb/sagnik/CORN_VS_PS/data/reference"

singularity exec \
-B ${ROOT_DIR}/data/PS_SALSA_annotation/alignments:${ROOT_DIR}/data/PS_SALSA_annotation/alignments \
${ROOT_DIR}/data/PS_SALSA_annotation/singularity_images/stringtie_2.2.1.sif \
bash -c "stringtie /project/maizegdb/sagnik/CORN_VS_PS/data/PS_SALSA_annotation/alignments/all_merged.bam -o /project/maizegdb/sagnik/CORN_VS_PS/data/PS_SALSA_annotation/alignments/stringtie_all_merged.gtf -m 100 -s 2 -p 72 1> /project/maizegdb/sagnik/CORN_VS_PS/data/PS_SALSA_annotation/alignments/stringtie_all_merged.output  2> /project/maizegdb/sagnik/CORN_VS_PS/data/PS_SALSA_annotation/alignments/stringtie_all_merged.error "

