#!/bin/bash

#SBATCH -n 40
#SBATCH -N 1
#SBATCH --partition=long
##SBATCH --partition=priority-mem768
#SBATCH --qos=maizegdb
#SBATCH --mem=100G
#SBATCH --time=14-00:00:00
#SBATCH --job-name="Fungal_Genome_Quality_Comparison"
#SBATCH --mail-user=sagnikbanerjee15@gmail.com
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/project/maizegdb/sagnik/CORN_VS_PS/data/Fungal_Genome_Quality_Comparison.output
#SBATCH --error=/project/maizegdb/sagnik/CORN_VS_PS/data/Fungal_Genome_Quality_Comparison.error

module load singularity

ROOT_DIR="/project/maizegdb/sagnik/CORN_VS_PS"
TEMP_DIR="/90daydata/maizegdb/sagnik/CORN_VS_PS"
REF_DIR="/90daydata/maizegdb/sagnik/CORN_VS_PS/data/reference"

${ROOT_DIR}/Corn_vs_PS/compareFungalGenomeQuality \
--metadata dummy \
--output_directory ${ROOT_DIR}/data/Fungal_Genome_Quality_Comparison \
--genome_references ${REF_DIR}/Argentina_PS.fa ${REF_DIR}/CR-IA16-P.sorghi-genome/SALSA/salsa_phase_hic.fasta ${REF_DIR}/CR-IA16-P.sorghi-genome/flye/flye_keep_haplotypes.fasta ${REF_DIR}/CR-IA16-P.sorghi-genome/falcon_unzip/flye_hap.phased.0.fasta ${REF_DIR}/CR-IA16-P.sorghi-genome/falcon_unzip/flye_hap.phased.1.fasta \
--cpu 40 \
--temp_directory ${TEMP_DIR}/Fungal_Genome_Quality_Comparison \
--transfer \
--framework singularity \
--pe_reads ${TEMP_DIR}/data/merged/S2/113  ${TEMP_DIR}/data/merged/S2/114 ${TEMP_DIR}/data/merged/S2/115 ${TEMP_DIR}/data/merged/S2/116 ${TEMP_DIR}/data/merged/S2/117 ${TEMP_DIR}/data/merged/S2/118 ${TEMP_DIR}/data/merged/S2/119 ${TEMP_DIR}/data/merged/S2/120 ${TEMP_DIR}/data/merged/S2/121 ${TEMP_DIR}/data/merged/S2/122 ${TEMP_DIR}/data/merged/SP/5 ${TEMP_DIR}/data/merged/SP/6 \
1> ${ROOT_DIR}/data/Fungal_Genome_Quality_Comparison.output \
2> ${ROOT_DIR}/data/Fungal_Genome_Quality_Comparison.error