#!/bin/bash

#SBATCH -n 40
#SBATCH -N 1
#SBATCH --partition=long
##SBATCH --partition=priority-mem768
#SBATCH --qos=maizegdb
#SBATCH --mem=100G
#SBATCH --time=1:00:00
#SBATCH --job-name="Fungal_Genome_Quality_Comparison"
#SBATCH --mail-user=sagnik@iastate.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=/project/maizegdb/sagnik/CORN_VS_PS/data/Fungal_Genome_Quality_Comparison.output
#SBATCH --error=/project/maizegdb/sagnik/CORN_VS_PS/data/Fungal_Genome_Quality_Comparison.error

module load singularity

ROOT_DIR="/project/maizegdb/sagnik/CORN_VS_PS"
TEMP_DIR="/90daydata/maizegdb/sagnik/CORN_VS_PS"

${ROOT_DIR}/Corn_vs_PS/compareFungalGenomeQuality \
--metadata dummy \
--output_directory ${ROOT_DIR}/data/Fungal_Genome_Quality_Comparison \
--genome_references \
--cpu 40 \
--temp_directory ${TEMP_DIR}/Fungal_Genome_Quality_Comparison \
--transfer \
--framework singularity \
1> ${ROOT_DIR}/data/Fungal_Genome_Quality_Comparison.output \
2> ${ROOT_DIR}/data/Fungal_Genome_Quality_Comparison.error